// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQqf1hYOXNgweLVOec6b-yjPkUJyiRwaQ',
    appId: '1:928753272286:web:114b1a60261c34a33c894f',
    messagingSenderId: '928753272286',
    projectId: 'gedungserbaguna',
    authDomain: 'gedungserbaguna.firebaseapp.com',
    storageBucket: 'gedungserbaguna.firebasestorage.app',
    measurementId: 'G-0ZT18QBVXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdiT121Z8gweDFR2Ed0IBdHobnMVkoYqs',
    appId: '1:928753272286:android:04ce93d3e923c5413c894f',
    messagingSenderId: '928753272286',
    projectId: 'gedungserbaguna',
    storageBucket: 'gedungserbaguna.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQqf1hYOXNgweLVOec6b-yjPkUJyiRwaQ',
    appId: '1:928753272286:web:dc6a007e9e91e6723c894f',
    messagingSenderId: '928753272286',
    projectId: 'gedungserbaguna',
    authDomain: 'gedungserbaguna.firebaseapp.com',
    storageBucket: 'gedungserbaguna.firebasestorage.app',
    measurementId: 'G-0ZJ4CHSK9T',
  );
}
